// Copyright 2026 Toly Pochkin
// SPDX-License-Identifier: Apache-2.0

package oversync

var retryableWriteManagedLayoutFacts = []managedLayoutFact{
	{Kind: "column", Identity: "sync.scope_write_receipts.auto_initialized", Attribute: "collation", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.auto_initialized", Attribute: "default", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.auto_initialized", Attribute: "generated", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.auto_initialized", Attribute: "identity", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.auto_initialized", Attribute: "not_null", Value: "false"},
	{Kind: "column", Identity: "sync.scope_write_receipts.auto_initialized", Attribute: "ordinal", Value: "15"},
	{Kind: "column", Identity: "sync.scope_write_receipts.auto_initialized", Attribute: "type", Value: "pg_catalog.bool"},
	{Kind: "column", Identity: "sync.scope_write_receipts.auto_initialized", Attribute: "typmod", Value: "-1"},
	{Kind: "column", Identity: "sync.scope_write_receipts.committed_bundle_hash", Attribute: "collation", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.committed_bundle_hash", Attribute: "default", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.committed_bundle_hash", Attribute: "generated", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.committed_bundle_hash", Attribute: "identity", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.committed_bundle_hash", Attribute: "not_null", Value: "false"},
	{Kind: "column", Identity: "sync.scope_write_receipts.committed_bundle_hash", Attribute: "ordinal", Value: "13"},
	{Kind: "column", Identity: "sync.scope_write_receipts.committed_bundle_hash", Attribute: "type", Value: "pg_catalog.bytea"},
	{Kind: "column", Identity: "sync.scope_write_receipts.committed_bundle_hash", Attribute: "typmod", Value: "-1"},
	{Kind: "column", Identity: "sync.scope_write_receipts.committed_bundle_seq", Attribute: "collation", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.committed_bundle_seq", Attribute: "default", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.committed_bundle_seq", Attribute: "generated", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.committed_bundle_seq", Attribute: "identity", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.committed_bundle_seq", Attribute: "not_null", Value: "false"},
	{Kind: "column", Identity: "sync.scope_write_receipts.committed_bundle_seq", Attribute: "ordinal", Value: "11"},
	{Kind: "column", Identity: "sync.scope_write_receipts.committed_bundle_seq", Attribute: "type", Value: "pg_catalog.int8"},
	{Kind: "column", Identity: "sync.scope_write_receipts.committed_bundle_seq", Attribute: "typmod", Value: "-1"},
	{Kind: "column", Identity: "sync.scope_write_receipts.committed_canonical_request_hash", Attribute: "collation", Value: "pg_catalog.C"},
	{Kind: "column", Identity: "sync.scope_write_receipts.committed_canonical_request_hash", Attribute: "default", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.committed_canonical_request_hash", Attribute: "generated", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.committed_canonical_request_hash", Attribute: "identity", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.committed_canonical_request_hash", Attribute: "not_null", Value: "false"},
	{Kind: "column", Identity: "sync.scope_write_receipts.committed_canonical_request_hash", Attribute: "ordinal", Value: "14"},
	{Kind: "column", Identity: "sync.scope_write_receipts.committed_canonical_request_hash", Attribute: "type", Value: "pg_catalog.text"},
	{Kind: "column", Identity: "sync.scope_write_receipts.committed_canonical_request_hash", Attribute: "typmod", Value: "-1"},
	{Kind: "column", Identity: "sync.scope_write_receipts.committed_row_count", Attribute: "collation", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.committed_row_count", Attribute: "default", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.committed_row_count", Attribute: "generated", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.committed_row_count", Attribute: "identity", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.committed_row_count", Attribute: "not_null", Value: "false"},
	{Kind: "column", Identity: "sync.scope_write_receipts.committed_row_count", Attribute: "ordinal", Value: "12"},
	{Kind: "column", Identity: "sync.scope_write_receipts.committed_row_count", Attribute: "type", Value: "pg_catalog.int8"},
	{Kind: "column", Identity: "sync.scope_write_receipts.committed_row_count", Attribute: "typmod", Value: "-1"},
	{Kind: "column", Identity: "sync.scope_write_receipts.committed_source_bundle_id", Attribute: "collation", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.committed_source_bundle_id", Attribute: "default", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.committed_source_bundle_id", Attribute: "generated", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.committed_source_bundle_id", Attribute: "identity", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.committed_source_bundle_id", Attribute: "not_null", Value: "false"},
	{Kind: "column", Identity: "sync.scope_write_receipts.committed_source_bundle_id", Attribute: "ordinal", Value: "10"},
	{Kind: "column", Identity: "sync.scope_write_receipts.committed_source_bundle_id", Attribute: "type", Value: "pg_catalog.int8"},
	{Kind: "column", Identity: "sync.scope_write_receipts.committed_source_bundle_id", Attribute: "typmod", Value: "-1"},
	{Kind: "column", Identity: "sync.scope_write_receipts.completed_at", Attribute: "collation", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.completed_at", Attribute: "default", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.completed_at", Attribute: "generated", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.completed_at", Attribute: "identity", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.completed_at", Attribute: "not_null", Value: "false"},
	{Kind: "column", Identity: "sync.scope_write_receipts.completed_at", Attribute: "ordinal", Value: "17"},
	{Kind: "column", Identity: "sync.scope_write_receipts.completed_at", Attribute: "type", Value: "pg_catalog.timestamptz"},
	{Kind: "column", Identity: "sync.scope_write_receipts.completed_at", Attribute: "typmod", Value: "-1"},
	{Kind: "column", Identity: "sync.scope_write_receipts.created_at", Attribute: "collation", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.created_at", Attribute: "default", Value: "transaction_timestamp()"},
	{Kind: "column", Identity: "sync.scope_write_receipts.created_at", Attribute: "generated", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.created_at", Attribute: "identity", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.created_at", Attribute: "not_null", Value: "true"},
	{Kind: "column", Identity: "sync.scope_write_receipts.created_at", Attribute: "ordinal", Value: "16"},
	{Kind: "column", Identity: "sync.scope_write_receipts.created_at", Attribute: "type", Value: "pg_catalog.timestamptz"},
	{Kind: "column", Identity: "sync.scope_write_receipts.created_at", Attribute: "typmod", Value: "-1"},
	{Kind: "column", Identity: "sync.scope_write_receipts.explicit_source_bundle_id", Attribute: "collation", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.explicit_source_bundle_id", Attribute: "default", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.explicit_source_bundle_id", Attribute: "generated", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.explicit_source_bundle_id", Attribute: "identity", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.explicit_source_bundle_id", Attribute: "not_null", Value: "false"},
	{Kind: "column", Identity: "sync.scope_write_receipts.explicit_source_bundle_id", Attribute: "ordinal", Value: "7"},
	{Kind: "column", Identity: "sync.scope_write_receipts.explicit_source_bundle_id", Attribute: "type", Value: "pg_catalog.int8"},
	{Kind: "column", Identity: "sync.scope_write_receipts.explicit_source_bundle_id", Attribute: "typmod", Value: "-1"},
	{Kind: "column", Identity: "sync.scope_write_receipts.forbidden_effect_tables_hash", Attribute: "collation", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.forbidden_effect_tables_hash", Attribute: "default", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.forbidden_effect_tables_hash", Attribute: "generated", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.forbidden_effect_tables_hash", Attribute: "identity", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.forbidden_effect_tables_hash", Attribute: "not_null", Value: "true"},
	{Kind: "column", Identity: "sync.scope_write_receipts.forbidden_effect_tables_hash", Attribute: "ordinal", Value: "5"},
	{Kind: "column", Identity: "sync.scope_write_receipts.forbidden_effect_tables_hash", Attribute: "type", Value: "pg_catalog.bytea"},
	{Kind: "column", Identity: "sync.scope_write_receipts.forbidden_effect_tables_hash", Attribute: "typmod", Value: "-1"},
	{Kind: "column", Identity: "sync.scope_write_receipts.operation_hash", Attribute: "collation", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.operation_hash", Attribute: "default", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.operation_hash", Attribute: "generated", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.operation_hash", Attribute: "identity", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.operation_hash", Attribute: "not_null", Value: "true"},
	{Kind: "column", Identity: "sync.scope_write_receipts.operation_hash", Attribute: "ordinal", Value: "3"},
	{Kind: "column", Identity: "sync.scope_write_receipts.operation_hash", Attribute: "type", Value: "pg_catalog.bytea"},
	{Kind: "column", Identity: "sync.scope_write_receipts.operation_hash", Attribute: "typmod", Value: "-1"},
	{Kind: "column", Identity: "sync.scope_write_receipts.operation_id", Attribute: "collation", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.operation_id", Attribute: "default", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.operation_id", Attribute: "generated", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.operation_id", Attribute: "identity", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.operation_id", Attribute: "not_null", Value: "true"},
	{Kind: "column", Identity: "sync.scope_write_receipts.operation_id", Attribute: "ordinal", Value: "2"},
	{Kind: "column", Identity: "sync.scope_write_receipts.operation_id", Attribute: "type", Value: "pg_catalog.uuid"},
	{Kind: "column", Identity: "sync.scope_write_receipts.operation_id", Attribute: "typmod", Value: "-1"},
	{Kind: "column", Identity: "sync.scope_write_receipts.operation_valid_until", Attribute: "collation", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.operation_valid_until", Attribute: "default", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.operation_valid_until", Attribute: "generated", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.operation_valid_until", Attribute: "identity", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.operation_valid_until", Attribute: "not_null", Value: "true"},
	{Kind: "column", Identity: "sync.scope_write_receipts.operation_valid_until", Attribute: "ordinal", Value: "8"},
	{Kind: "column", Identity: "sync.scope_write_receipts.operation_valid_until", Attribute: "type", Value: "pg_catalog.timestamptz"},
	{Kind: "column", Identity: "sync.scope_write_receipts.operation_valid_until", Attribute: "typmod", Value: "-1"},
	{Kind: "column", Identity: "sync.scope_write_receipts.receipt_expires_at", Attribute: "collation", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.receipt_expires_at", Attribute: "default", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.receipt_expires_at", Attribute: "generated", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.receipt_expires_at", Attribute: "identity", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.receipt_expires_at", Attribute: "not_null", Value: "true"},
	{Kind: "column", Identity: "sync.scope_write_receipts.receipt_expires_at", Attribute: "ordinal", Value: "18"},
	{Kind: "column", Identity: "sync.scope_write_receipts.receipt_expires_at", Attribute: "type", Value: "pg_catalog.timestamptz"},
	{Kind: "column", Identity: "sync.scope_write_receipts.receipt_expires_at", Attribute: "typmod", Value: "-1"},
	{Kind: "column", Identity: "sync.scope_write_receipts.receipt_state", Attribute: "collation", Value: "pg_catalog.C"},
	{Kind: "column", Identity: "sync.scope_write_receipts.receipt_state", Attribute: "default", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.receipt_state", Attribute: "generated", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.receipt_state", Attribute: "identity", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.receipt_state", Attribute: "not_null", Value: "true"},
	{Kind: "column", Identity: "sync.scope_write_receipts.receipt_state", Attribute: "ordinal", Value: "9"},
	{Kind: "column", Identity: "sync.scope_write_receipts.receipt_state", Attribute: "type", Value: "pg_catalog.text"},
	{Kind: "column", Identity: "sync.scope_write_receipts.receipt_state", Attribute: "typmod", Value: "-1"},
	{Kind: "column", Identity: "sync.scope_write_receipts.required_effect_tables_hash", Attribute: "collation", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.required_effect_tables_hash", Attribute: "default", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.required_effect_tables_hash", Attribute: "generated", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.required_effect_tables_hash", Attribute: "identity", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.required_effect_tables_hash", Attribute: "not_null", Value: "true"},
	{Kind: "column", Identity: "sync.scope_write_receipts.required_effect_tables_hash", Attribute: "ordinal", Value: "4"},
	{Kind: "column", Identity: "sync.scope_write_receipts.required_effect_tables_hash", Attribute: "type", Value: "pg_catalog.bytea"},
	{Kind: "column", Identity: "sync.scope_write_receipts.required_effect_tables_hash", Attribute: "typmod", Value: "-1"},
	{Kind: "column", Identity: "sync.scope_write_receipts.user_pk", Attribute: "collation", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.user_pk", Attribute: "default", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.user_pk", Attribute: "generated", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.user_pk", Attribute: "identity", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.user_pk", Attribute: "not_null", Value: "true"},
	{Kind: "column", Identity: "sync.scope_write_receipts.user_pk", Attribute: "ordinal", Value: "1"},
	{Kind: "column", Identity: "sync.scope_write_receipts.user_pk", Attribute: "type", Value: "pg_catalog.int8"},
	{Kind: "column", Identity: "sync.scope_write_receipts.user_pk", Attribute: "typmod", Value: "-1"},
	{Kind: "column", Identity: "sync.scope_write_receipts.writer_id", Attribute: "collation", Value: "pg_catalog.C"},
	{Kind: "column", Identity: "sync.scope_write_receipts.writer_id", Attribute: "default", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.writer_id", Attribute: "generated", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.writer_id", Attribute: "identity", Value: ""},
	{Kind: "column", Identity: "sync.scope_write_receipts.writer_id", Attribute: "not_null", Value: "true"},
	{Kind: "column", Identity: "sync.scope_write_receipts.writer_id", Attribute: "ordinal", Value: "6"},
	{Kind: "column", Identity: "sync.scope_write_receipts.writer_id", Attribute: "type", Value: "pg_catalog.text"},
	{Kind: "column", Identity: "sync.scope_write_receipts.writer_id", Attribute: "typmod", Value: "-1"},
	{Kind: "column", Identity: "sync.server_source_reservations.ever_used", Attribute: "collation", Value: ""},
	{Kind: "column", Identity: "sync.server_source_reservations.ever_used", Attribute: "default", Value: "false"},
	{Kind: "column", Identity: "sync.server_source_reservations.ever_used", Attribute: "generated", Value: ""},
	{Kind: "column", Identity: "sync.server_source_reservations.ever_used", Attribute: "identity", Value: ""},
	{Kind: "column", Identity: "sync.server_source_reservations.ever_used", Attribute: "not_null", Value: "true"},
	{Kind: "column", Identity: "sync.server_source_reservations.ever_used", Attribute: "ordinal", Value: "2"},
	{Kind: "column", Identity: "sync.server_source_reservations.ever_used", Attribute: "type", Value: "pg_catalog.bool"},
	{Kind: "column", Identity: "sync.server_source_reservations.ever_used", Attribute: "typmod", Value: "-1"},
	{Kind: "column", Identity: "sync.server_source_reservations.source_id", Attribute: "collation", Value: "pg_catalog.C"},
	{Kind: "column", Identity: "sync.server_source_reservations.source_id", Attribute: "default", Value: ""},
	{Kind: "column", Identity: "sync.server_source_reservations.source_id", Attribute: "generated", Value: ""},
	{Kind: "column", Identity: "sync.server_source_reservations.source_id", Attribute: "identity", Value: ""},
	{Kind: "column", Identity: "sync.server_source_reservations.source_id", Attribute: "not_null", Value: "true"},
	{Kind: "column", Identity: "sync.server_source_reservations.source_id", Attribute: "ordinal", Value: "1"},
	{Kind: "column", Identity: "sync.server_source_reservations.source_id", Attribute: "type", Value: "pg_catalog.text"},
	{Kind: "column", Identity: "sync.server_source_reservations.source_id", Attribute: "typmod", Value: "-1"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_check", Attribute: "columns", Value: "[\"operation_valid_until\",\"receipt_expires_at\"]"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_check", Attribute: "deferrable", Value: "false"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_check", Attribute: "delete_action", Value: " "},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_check", Attribute: "expression", Value: "(isfinite(operation_valid_until) AND isfinite(receipt_expires_at))"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_check", Attribute: "initially_deferred", Value: "false"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_check", Attribute: "match_type", Value: " "},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_check", Attribute: "referenced_columns", Value: "[]"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_check", Attribute: "referenced_table", Value: ""},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_check", Attribute: "type", Value: "c"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_check", Attribute: "update_action", Value: " "},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_check", Attribute: "validated", Value: "true"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_check1", Attribute: "columns", Value: "[\"operation_valid_until\",\"receipt_expires_at\"]"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_check1", Attribute: "deferrable", Value: "false"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_check1", Attribute: "delete_action", Value: " "},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_check1", Attribute: "expression", Value: "((operation_valid_until >= '0001-01-01 00:00:00+00'::timestamp with time zone) AND (receipt_expires_at < '10000-01-01 00:00:00+00'::timestamp with time zone))"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_check1", Attribute: "initially_deferred", Value: "false"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_check1", Attribute: "match_type", Value: " "},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_check1", Attribute: "referenced_columns", Value: "[]"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_check1", Attribute: "referenced_table", Value: ""},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_check1", Attribute: "type", Value: "c"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_check1", Attribute: "update_action", Value: " "},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_check1", Attribute: "validated", Value: "true"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_check2", Attribute: "columns", Value: "[\"receipt_state\",\"committed_source_bundle_id\",\"committed_bundle_seq\",\"committed_row_count\",\"committed_bundle_hash\",\"committed_canonical_request_hash\",\"auto_initialized\",\"completed_at\",\"receipt_expires_at\",\"operation_valid_until\"]"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_check2", Attribute: "deferrable", Value: "false"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_check2", Attribute: "delete_action", Value: " "},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_check2", Attribute: "expression", Value: "(((receipt_state = 'in_progress'::text) AND (committed_source_bundle_id IS NULL) AND (committed_bundle_seq IS NULL) AND (committed_row_count IS NULL) AND (committed_bundle_hash IS NULL) AND (committed_canonical_request_hash IS NULL) AND (auto_initialized IS NULL) AND (completed_at IS NULL) AND (receipt_expires_at = (operation_valid_until + '24:00:00'::interval))) OR ((receipt_state = 'completed'::text) AND (committed_source_bundle_id IS NOT NULL) AND (committed_source_bundle_id > 0) AND (committed_bundle_seq IS NOT NULL) AND (committed_bundle_seq > 0) AND (committed_row_count IS NOT NULL) AND (committed_row_count > 0) AND (committed_bundle_hash IS NOT NULL) AND (octet_length(committed_bundle_hash) = 32) AND (committed_canonical_request_hash IS NOT NULL) AND (auto_initialized IS NOT NULL) AND (completed_at IS NOT NULL) AND (receipt_expires_at = (GREATEST(operation_valid_until, completed_at) + '24:00:00'::interval))))"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_check2", Attribute: "initially_deferred", Value: "false"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_check2", Attribute: "match_type", Value: " "},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_check2", Attribute: "referenced_columns", Value: "[]"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_check2", Attribute: "referenced_table", Value: ""},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_check2", Attribute: "type", Value: "c"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_check2", Attribute: "update_action", Value: " "},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_check2", Attribute: "validated", Value: "true"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_check3", Attribute: "columns", Value: "[\"receipt_state\",\"explicit_source_bundle_id\",\"committed_source_bundle_id\"]"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_check3", Attribute: "deferrable", Value: "false"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_check3", Attribute: "delete_action", Value: " "},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_check3", Attribute: "expression", Value: "((receipt_state <> 'completed'::text) OR (explicit_source_bundle_id IS NULL) OR (committed_source_bundle_id = explicit_source_bundle_id))"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_check3", Attribute: "initially_deferred", Value: "false"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_check3", Attribute: "match_type", Value: " "},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_check3", Attribute: "referenced_columns", Value: "[]"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_check3", Attribute: "referenced_table", Value: ""},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_check3", Attribute: "type", Value: "c"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_check3", Attribute: "update_action", Value: " "},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_check3", Attribute: "validated", Value: "true"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_committed_canonical_request_hash_check", Attribute: "columns", Value: "[\"committed_canonical_request_hash\"]"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_committed_canonical_request_hash_check", Attribute: "deferrable", Value: "false"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_committed_canonical_request_hash_check", Attribute: "delete_action", Value: " "},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_committed_canonical_request_hash_check", Attribute: "expression", Value: "((committed_canonical_request_hash IS NULL) OR (committed_canonical_request_hash = ''::text) OR (committed_canonical_request_hash ~ '^[0-9a-f]{64}$'::text))"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_committed_canonical_request_hash_check", Attribute: "initially_deferred", Value: "false"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_committed_canonical_request_hash_check", Attribute: "match_type", Value: " "},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_committed_canonical_request_hash_check", Attribute: "referenced_columns", Value: "[]"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_committed_canonical_request_hash_check", Attribute: "referenced_table", Value: ""},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_committed_canonical_request_hash_check", Attribute: "type", Value: "c"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_committed_canonical_request_hash_check", Attribute: "update_action", Value: " "},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_committed_canonical_request_hash_check", Attribute: "validated", Value: "true"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_explicit_source_bundle_id_check", Attribute: "columns", Value: "[\"explicit_source_bundle_id\"]"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_explicit_source_bundle_id_check", Attribute: "deferrable", Value: "false"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_explicit_source_bundle_id_check", Attribute: "delete_action", Value: " "},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_explicit_source_bundle_id_check", Attribute: "expression", Value: "((explicit_source_bundle_id IS NULL) OR (explicit_source_bundle_id > 0))"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_explicit_source_bundle_id_check", Attribute: "initially_deferred", Value: "false"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_explicit_source_bundle_id_check", Attribute: "match_type", Value: " "},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_explicit_source_bundle_id_check", Attribute: "referenced_columns", Value: "[]"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_explicit_source_bundle_id_check", Attribute: "referenced_table", Value: ""},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_explicit_source_bundle_id_check", Attribute: "type", Value: "c"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_explicit_source_bundle_id_check", Attribute: "update_action", Value: " "},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_explicit_source_bundle_id_check", Attribute: "validated", Value: "true"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_finalizer", Attribute: "columns", Value: "[]"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_finalizer", Attribute: "deferrable", Value: "true"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_finalizer", Attribute: "delete_action", Value: " "},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_finalizer", Attribute: "expression", Value: ""},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_finalizer", Attribute: "initially_deferred", Value: "true"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_finalizer", Attribute: "match_type", Value: " "},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_finalizer", Attribute: "referenced_columns", Value: "[]"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_finalizer", Attribute: "referenced_table", Value: ""},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_finalizer", Attribute: "type", Value: "t"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_finalizer", Attribute: "update_action", Value: " "},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_finalizer", Attribute: "validated", Value: "true"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_forbidden_effect_tables_hash_check", Attribute: "columns", Value: "[\"forbidden_effect_tables_hash\"]"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_forbidden_effect_tables_hash_check", Attribute: "deferrable", Value: "false"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_forbidden_effect_tables_hash_check", Attribute: "delete_action", Value: " "},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_forbidden_effect_tables_hash_check", Attribute: "expression", Value: "(octet_length(forbidden_effect_tables_hash) = 32)"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_forbidden_effect_tables_hash_check", Attribute: "initially_deferred", Value: "false"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_forbidden_effect_tables_hash_check", Attribute: "match_type", Value: " "},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_forbidden_effect_tables_hash_check", Attribute: "referenced_columns", Value: "[]"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_forbidden_effect_tables_hash_check", Attribute: "referenced_table", Value: ""},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_forbidden_effect_tables_hash_check", Attribute: "type", Value: "c"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_forbidden_effect_tables_hash_check", Attribute: "update_action", Value: " "},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_forbidden_effect_tables_hash_check", Attribute: "validated", Value: "true"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_operation_hash_check", Attribute: "columns", Value: "[\"operation_hash\"]"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_operation_hash_check", Attribute: "deferrable", Value: "false"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_operation_hash_check", Attribute: "delete_action", Value: " "},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_operation_hash_check", Attribute: "expression", Value: "(octet_length(operation_hash) = 32)"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_operation_hash_check", Attribute: "initially_deferred", Value: "false"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_operation_hash_check", Attribute: "match_type", Value: " "},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_operation_hash_check", Attribute: "referenced_columns", Value: "[]"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_operation_hash_check", Attribute: "referenced_table", Value: ""},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_operation_hash_check", Attribute: "type", Value: "c"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_operation_hash_check", Attribute: "update_action", Value: " "},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_operation_hash_check", Attribute: "validated", Value: "true"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_operation_id_check", Attribute: "columns", Value: "[\"operation_id\"]"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_operation_id_check", Attribute: "deferrable", Value: "false"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_operation_id_check", Attribute: "delete_action", Value: " "},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_operation_id_check", Attribute: "expression", Value: "(operation_id <> '00000000-0000-0000-0000-000000000000'::uuid)"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_operation_id_check", Attribute: "initially_deferred", Value: "false"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_operation_id_check", Attribute: "match_type", Value: " "},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_operation_id_check", Attribute: "referenced_columns", Value: "[]"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_operation_id_check", Attribute: "referenced_table", Value: ""},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_operation_id_check", Attribute: "type", Value: "c"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_operation_id_check", Attribute: "update_action", Value: " "},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_operation_id_check", Attribute: "validated", Value: "true"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_pkey", Attribute: "columns", Value: "[\"user_pk\",\"operation_id\"]"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_pkey", Attribute: "deferrable", Value: "false"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_pkey", Attribute: "delete_action", Value: " "},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_pkey", Attribute: "expression", Value: ""},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_pkey", Attribute: "initially_deferred", Value: "false"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_pkey", Attribute: "match_type", Value: " "},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_pkey", Attribute: "referenced_columns", Value: "[]"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_pkey", Attribute: "referenced_table", Value: ""},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_pkey", Attribute: "type", Value: "p"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_pkey", Attribute: "update_action", Value: " "},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_pkey", Attribute: "validated", Value: "true"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_receipt_state_check", Attribute: "columns", Value: "[\"receipt_state\"]"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_receipt_state_check", Attribute: "deferrable", Value: "false"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_receipt_state_check", Attribute: "delete_action", Value: " "},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_receipt_state_check", Attribute: "expression", Value: "(receipt_state = ANY (ARRAY['in_progress'::text, 'completed'::text]))"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_receipt_state_check", Attribute: "initially_deferred", Value: "false"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_receipt_state_check", Attribute: "match_type", Value: " "},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_receipt_state_check", Attribute: "referenced_columns", Value: "[]"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_receipt_state_check", Attribute: "referenced_table", Value: ""},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_receipt_state_check", Attribute: "type", Value: "c"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_receipt_state_check", Attribute: "update_action", Value: " "},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_receipt_state_check", Attribute: "validated", Value: "true"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_required_effect_tables_hash_check", Attribute: "columns", Value: "[\"required_effect_tables_hash\"]"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_required_effect_tables_hash_check", Attribute: "deferrable", Value: "false"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_required_effect_tables_hash_check", Attribute: "delete_action", Value: " "},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_required_effect_tables_hash_check", Attribute: "expression", Value: "(octet_length(required_effect_tables_hash) = 32)"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_required_effect_tables_hash_check", Attribute: "initially_deferred", Value: "false"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_required_effect_tables_hash_check", Attribute: "match_type", Value: " "},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_required_effect_tables_hash_check", Attribute: "referenced_columns", Value: "[]"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_required_effect_tables_hash_check", Attribute: "referenced_table", Value: ""},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_required_effect_tables_hash_check", Attribute: "type", Value: "c"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_required_effect_tables_hash_check", Attribute: "update_action", Value: " "},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_required_effect_tables_hash_check", Attribute: "validated", Value: "true"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_user_pk_fkey", Attribute: "columns", Value: "[\"user_pk\"]"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_user_pk_fkey", Attribute: "deferrable", Value: "false"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_user_pk_fkey", Attribute: "delete_action", Value: "c"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_user_pk_fkey", Attribute: "expression", Value: ""},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_user_pk_fkey", Attribute: "initially_deferred", Value: "false"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_user_pk_fkey", Attribute: "match_type", Value: "s"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_user_pk_fkey", Attribute: "referenced_columns", Value: "[\"user_pk\"]"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_user_pk_fkey", Attribute: "referenced_table", Value: "sync.user_state"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_user_pk_fkey", Attribute: "type", Value: "f"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_user_pk_fkey", Attribute: "update_action", Value: "a"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_user_pk_fkey", Attribute: "validated", Value: "true"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_writer_id_check", Attribute: "columns", Value: "[\"writer_id\"]"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_writer_id_check", Attribute: "deferrable", Value: "false"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_writer_id_check", Attribute: "delete_action", Value: " "},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_writer_id_check", Attribute: "expression", Value: "(writer_id <> ''::text)"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_writer_id_check", Attribute: "initially_deferred", Value: "false"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_writer_id_check", Attribute: "match_type", Value: " "},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_writer_id_check", Attribute: "referenced_columns", Value: "[]"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_writer_id_check", Attribute: "referenced_table", Value: ""},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_writer_id_check", Attribute: "type", Value: "c"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_writer_id_check", Attribute: "update_action", Value: " "},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_writer_id_check", Attribute: "validated", Value: "true"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_writer_id_check1", Attribute: "columns", Value: "[\"writer_id\"]"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_writer_id_check1", Attribute: "deferrable", Value: "false"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_writer_id_check1", Attribute: "delete_action", Value: " "},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_writer_id_check1", Attribute: "expression", Value: "(writer_id ~ '^[!-~]+$'::text)"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_writer_id_check1", Attribute: "initially_deferred", Value: "false"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_writer_id_check1", Attribute: "match_type", Value: " "},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_writer_id_check1", Attribute: "referenced_columns", Value: "[]"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_writer_id_check1", Attribute: "referenced_table", Value: ""},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_writer_id_check1", Attribute: "type", Value: "c"},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_writer_id_check1", Attribute: "update_action", Value: " "},
	{Kind: "constraint", Identity: "sync.scope_write_receipts.scope_write_receipts_writer_id_check1", Attribute: "validated", Value: "true"},
	{Kind: "constraint", Identity: "sync.server_source_reservations.server_source_reservations_pkey", Attribute: "columns", Value: "[\"source_id\"]"},
	{Kind: "constraint", Identity: "sync.server_source_reservations.server_source_reservations_pkey", Attribute: "deferrable", Value: "false"},
	{Kind: "constraint", Identity: "sync.server_source_reservations.server_source_reservations_pkey", Attribute: "delete_action", Value: " "},
	{Kind: "constraint", Identity: "sync.server_source_reservations.server_source_reservations_pkey", Attribute: "expression", Value: ""},
	{Kind: "constraint", Identity: "sync.server_source_reservations.server_source_reservations_pkey", Attribute: "initially_deferred", Value: "false"},
	{Kind: "constraint", Identity: "sync.server_source_reservations.server_source_reservations_pkey", Attribute: "match_type", Value: " "},
	{Kind: "constraint", Identity: "sync.server_source_reservations.server_source_reservations_pkey", Attribute: "referenced_columns", Value: "[]"},
	{Kind: "constraint", Identity: "sync.server_source_reservations.server_source_reservations_pkey", Attribute: "referenced_table", Value: ""},
	{Kind: "constraint", Identity: "sync.server_source_reservations.server_source_reservations_pkey", Attribute: "type", Value: "p"},
	{Kind: "constraint", Identity: "sync.server_source_reservations.server_source_reservations_pkey", Attribute: "update_action", Value: " "},
	{Kind: "constraint", Identity: "sync.server_source_reservations.server_source_reservations_pkey", Attribute: "validated", Value: "true"},
	{Kind: "constraint", Identity: "sync.server_source_reservations.server_source_reservations_source_id_check", Attribute: "columns", Value: "[\"source_id\"]"},
	{Kind: "constraint", Identity: "sync.server_source_reservations.server_source_reservations_source_id_check", Attribute: "deferrable", Value: "false"},
	{Kind: "constraint", Identity: "sync.server_source_reservations.server_source_reservations_source_id_check", Attribute: "delete_action", Value: " "},
	{Kind: "constraint", Identity: "sync.server_source_reservations.server_source_reservations_source_id_check", Attribute: "expression", Value: "((octet_length(source_id) >= 1) AND (octet_length(source_id) <= 256))"},
	{Kind: "constraint", Identity: "sync.server_source_reservations.server_source_reservations_source_id_check", Attribute: "initially_deferred", Value: "false"},
	{Kind: "constraint", Identity: "sync.server_source_reservations.server_source_reservations_source_id_check", Attribute: "match_type", Value: " "},
	{Kind: "constraint", Identity: "sync.server_source_reservations.server_source_reservations_source_id_check", Attribute: "referenced_columns", Value: "[]"},
	{Kind: "constraint", Identity: "sync.server_source_reservations.server_source_reservations_source_id_check", Attribute: "referenced_table", Value: ""},
	{Kind: "constraint", Identity: "sync.server_source_reservations.server_source_reservations_source_id_check", Attribute: "type", Value: "c"},
	{Kind: "constraint", Identity: "sync.server_source_reservations.server_source_reservations_source_id_check", Attribute: "update_action", Value: " "},
	{Kind: "constraint", Identity: "sync.server_source_reservations.server_source_reservations_source_id_check", Attribute: "validated", Value: "true"},
	{Kind: "constraint", Identity: "sync.server_source_reservations.server_source_reservations_source_id_check1", Attribute: "columns", Value: "[\"source_id\"]"},
	{Kind: "constraint", Identity: "sync.server_source_reservations.server_source_reservations_source_id_check1", Attribute: "deferrable", Value: "false"},
	{Kind: "constraint", Identity: "sync.server_source_reservations.server_source_reservations_source_id_check1", Attribute: "delete_action", Value: " "},
	{Kind: "constraint", Identity: "sync.server_source_reservations.server_source_reservations_source_id_check1", Attribute: "expression", Value: "(source_id ~ '^[!-~]+$'::text)"},
	{Kind: "constraint", Identity: "sync.server_source_reservations.server_source_reservations_source_id_check1", Attribute: "initially_deferred", Value: "false"},
	{Kind: "constraint", Identity: "sync.server_source_reservations.server_source_reservations_source_id_check1", Attribute: "match_type", Value: " "},
	{Kind: "constraint", Identity: "sync.server_source_reservations.server_source_reservations_source_id_check1", Attribute: "referenced_columns", Value: "[]"},
	{Kind: "constraint", Identity: "sync.server_source_reservations.server_source_reservations_source_id_check1", Attribute: "referenced_table", Value: ""},
	{Kind: "constraint", Identity: "sync.server_source_reservations.server_source_reservations_source_id_check1", Attribute: "type", Value: "c"},
	{Kind: "constraint", Identity: "sync.server_source_reservations.server_source_reservations_source_id_check1", Attribute: "update_action", Value: " "},
	{Kind: "constraint", Identity: "sync.server_source_reservations.server_source_reservations_source_id_check1", Attribute: "validated", Value: "true"},
	{Kind: "function", Identity: "sync.finalize_scope_write_receipt()", Attribute: "configuration", Value: "[]"},
	{Kind: "function", Identity: "sync.finalize_scope_write_receipt()", Attribute: "language", Value: "plpgsql"},
	{Kind: "function", Identity: "sync.finalize_scope_write_receipt()", Attribute: "leakproof", Value: "false"},
	{Kind: "function", Identity: "sync.finalize_scope_write_receipt()", Attribute: "parallel", Value: "u"},
	{Kind: "function", Identity: "sync.finalize_scope_write_receipt()", Attribute: "return_type", Value: "pg_catalog.trigger"},
	{Kind: "function", Identity: "sync.finalize_scope_write_receipt()", Attribute: "security_definer", Value: "false"},
	{Kind: "function", Identity: "sync.finalize_scope_write_receipt()", Attribute: "source.sha256", Value: "4e2b4540519ddad4254a6ae05862d8c1918aa273b0380e210470379ce98b2bce"},
	{Kind: "function", Identity: "sync.finalize_scope_write_receipt()", Attribute: "strict", Value: "false"},
	{Kind: "function", Identity: "sync.finalize_scope_write_receipt()", Attribute: "volatility", Value: "v"},
	{Kind: "function", Identity: "sync.guard_server_source_reservation()", Attribute: "configuration", Value: "[]"},
	{Kind: "function", Identity: "sync.guard_server_source_reservation()", Attribute: "language", Value: "plpgsql"},
	{Kind: "function", Identity: "sync.guard_server_source_reservation()", Attribute: "leakproof", Value: "false"},
	{Kind: "function", Identity: "sync.guard_server_source_reservation()", Attribute: "parallel", Value: "u"},
	{Kind: "function", Identity: "sync.guard_server_source_reservation()", Attribute: "return_type", Value: "pg_catalog.trigger"},
	{Kind: "function", Identity: "sync.guard_server_source_reservation()", Attribute: "security_definer", Value: "false"},
	{Kind: "function", Identity: "sync.guard_server_source_reservation()", Attribute: "source.sha256", Value: "5f2a909f616f77590cd1d10a239a710a1b10661df0fc36a4dfd9d9ce8d99e3dc"},
	{Kind: "function", Identity: "sync.guard_server_source_reservation()", Attribute: "strict", Value: "false"},
	{Kind: "function", Identity: "sync.guard_server_source_reservation()", Attribute: "volatility", Value: "v"},
	{Kind: "index", Identity: "sync.scope_write_receipts_cleanup_idx", Attribute: "access_method", Value: "btree"},
	{Kind: "index", Identity: "sync.scope_write_receipts_cleanup_idx", Attribute: "attribute.1", Value: "{\"role\": \"key\", \"column\": \"receipt_expires_at\", \"opclass\": \"pg_catalog.timestamptz_ops\", \"collation\": \"\", \"descending\": false, \"expression\": \"\", \"nulls_first\": false}"},
	{Kind: "index", Identity: "sync.scope_write_receipts_cleanup_idx", Attribute: "attribute.2", Value: "{\"role\": \"key\", \"column\": \"user_pk\", \"opclass\": \"pg_catalog.int8_ops\", \"collation\": \"\", \"descending\": false, \"expression\": \"\", \"nulls_first\": false}"},
	{Kind: "index", Identity: "sync.scope_write_receipts_cleanup_idx", Attribute: "attribute.3", Value: "{\"role\": \"key\", \"column\": \"operation_id\", \"opclass\": \"pg_catalog.uuid_ops\", \"collation\": \"\", \"descending\": false, \"expression\": \"\", \"nulls_first\": false}"},
	{Kind: "index", Identity: "sync.scope_write_receipts_cleanup_idx", Attribute: "attribute_count", Value: "3"},
	{Kind: "index", Identity: "sync.scope_write_receipts_cleanup_idx", Attribute: "exclusion", Value: "false"},
	{Kind: "index", Identity: "sync.scope_write_receipts_cleanup_idx", Attribute: "key_count", Value: "3"},
	{Kind: "index", Identity: "sync.scope_write_receipts_cleanup_idx", Attribute: "live", Value: "true"},
	{Kind: "index", Identity: "sync.scope_write_receipts_cleanup_idx", Attribute: "predicate", Value: "(receipt_state = 'completed'::text)"},
	{Kind: "index", Identity: "sync.scope_write_receipts_cleanup_idx", Attribute: "primary", Value: "false"},
	{Kind: "index", Identity: "sync.scope_write_receipts_cleanup_idx", Attribute: "ready", Value: "true"},
	{Kind: "index", Identity: "sync.scope_write_receipts_cleanup_idx", Attribute: "table", Value: "sync.scope_write_receipts"},
	{Kind: "index", Identity: "sync.scope_write_receipts_cleanup_idx", Attribute: "unique", Value: "false"},
	{Kind: "index", Identity: "sync.scope_write_receipts_cleanup_idx", Attribute: "valid", Value: "true"},
	{Kind: "index", Identity: "sync.scope_write_receipts_pkey", Attribute: "access_method", Value: "btree"},
	{Kind: "index", Identity: "sync.scope_write_receipts_pkey", Attribute: "attribute.1", Value: "{\"role\": \"key\", \"column\": \"user_pk\", \"opclass\": \"pg_catalog.int8_ops\", \"collation\": \"\", \"descending\": false, \"expression\": \"\", \"nulls_first\": false}"},
	{Kind: "index", Identity: "sync.scope_write_receipts_pkey", Attribute: "attribute.2", Value: "{\"role\": \"key\", \"column\": \"operation_id\", \"opclass\": \"pg_catalog.uuid_ops\", \"collation\": \"\", \"descending\": false, \"expression\": \"\", \"nulls_first\": false}"},
	{Kind: "index", Identity: "sync.scope_write_receipts_pkey", Attribute: "attribute_count", Value: "2"},
	{Kind: "index", Identity: "sync.scope_write_receipts_pkey", Attribute: "exclusion", Value: "false"},
	{Kind: "index", Identity: "sync.scope_write_receipts_pkey", Attribute: "key_count", Value: "2"},
	{Kind: "index", Identity: "sync.scope_write_receipts_pkey", Attribute: "live", Value: "true"},
	{Kind: "index", Identity: "sync.scope_write_receipts_pkey", Attribute: "predicate", Value: ""},
	{Kind: "index", Identity: "sync.scope_write_receipts_pkey", Attribute: "primary", Value: "true"},
	{Kind: "index", Identity: "sync.scope_write_receipts_pkey", Attribute: "ready", Value: "true"},
	{Kind: "index", Identity: "sync.scope_write_receipts_pkey", Attribute: "table", Value: "sync.scope_write_receipts"},
	{Kind: "index", Identity: "sync.scope_write_receipts_pkey", Attribute: "unique", Value: "true"},
	{Kind: "index", Identity: "sync.scope_write_receipts_pkey", Attribute: "valid", Value: "true"},
	{Kind: "index", Identity: "sync.server_source_reservations_pkey", Attribute: "access_method", Value: "btree"},
	{Kind: "index", Identity: "sync.server_source_reservations_pkey", Attribute: "attribute.1", Value: "{\"role\": \"key\", \"column\": \"source_id\", \"opclass\": \"pg_catalog.text_ops\", \"collation\": \"pg_catalog.C\", \"descending\": false, \"expression\": \"\", \"nulls_first\": false}"},
	{Kind: "index", Identity: "sync.server_source_reservations_pkey", Attribute: "attribute_count", Value: "1"},
	{Kind: "index", Identity: "sync.server_source_reservations_pkey", Attribute: "exclusion", Value: "false"},
	{Kind: "index", Identity: "sync.server_source_reservations_pkey", Attribute: "key_count", Value: "1"},
	{Kind: "index", Identity: "sync.server_source_reservations_pkey", Attribute: "live", Value: "true"},
	{Kind: "index", Identity: "sync.server_source_reservations_pkey", Attribute: "predicate", Value: ""},
	{Kind: "index", Identity: "sync.server_source_reservations_pkey", Attribute: "primary", Value: "true"},
	{Kind: "index", Identity: "sync.server_source_reservations_pkey", Attribute: "ready", Value: "true"},
	{Kind: "index", Identity: "sync.server_source_reservations_pkey", Attribute: "table", Value: "sync.server_source_reservations"},
	{Kind: "index", Identity: "sync.server_source_reservations_pkey", Attribute: "unique", Value: "true"},
	{Kind: "index", Identity: "sync.server_source_reservations_pkey", Attribute: "valid", Value: "true"},
	{Kind: "relation", Identity: "sync.scope_write_receipts", Attribute: "force_row_security", Value: "false"},
	{Kind: "relation", Identity: "sync.scope_write_receipts", Attribute: "is_partition", Value: "false"},
	{Kind: "relation", Identity: "sync.scope_write_receipts", Attribute: "kind", Value: "r"},
	{Kind: "relation", Identity: "sync.scope_write_receipts", Attribute: "persistence", Value: "p"},
	{Kind: "relation", Identity: "sync.scope_write_receipts", Attribute: "replica_identity", Value: "d"},
	{Kind: "relation", Identity: "sync.scope_write_receipts", Attribute: "row_security", Value: "false"},
	{Kind: "relation", Identity: "sync.server_source_reservations", Attribute: "force_row_security", Value: "false"},
	{Kind: "relation", Identity: "sync.server_source_reservations", Attribute: "is_partition", Value: "false"},
	{Kind: "relation", Identity: "sync.server_source_reservations", Attribute: "kind", Value: "r"},
	{Kind: "relation", Identity: "sync.server_source_reservations", Attribute: "persistence", Value: "p"},
	{Kind: "relation", Identity: "sync.server_source_reservations", Attribute: "replica_identity", Value: "d"},
	{Kind: "relation", Identity: "sync.server_source_reservations", Attribute: "row_security", Value: "false"},
	{Kind: "trigger", Identity: "sync.scope_write_receipts.scope_write_receipts_finalizer", Attribute: "arguments", Value: "[]"},
	{Kind: "trigger", Identity: "sync.scope_write_receipts.scope_write_receipts_finalizer", Attribute: "constraint", Value: "sync.scope_write_receipts.scope_write_receipts_finalizer"},
	{Kind: "trigger", Identity: "sync.scope_write_receipts.scope_write_receipts_finalizer", Attribute: "enabled", Value: "O"},
	{Kind: "trigger", Identity: "sync.scope_write_receipts.scope_write_receipts_finalizer", Attribute: "events", Value: "insert,update"},
	{Kind: "trigger", Identity: "sync.scope_write_receipts.scope_write_receipts_finalizer", Attribute: "function", Value: "sync.finalize_scope_write_receipt()"},
	{Kind: "trigger", Identity: "sync.scope_write_receipts.scope_write_receipts_finalizer", Attribute: "level", Value: "row"},
	{Kind: "trigger", Identity: "sync.scope_write_receipts.scope_write_receipts_finalizer", Attribute: "new_transition", Value: ""},
	{Kind: "trigger", Identity: "sync.scope_write_receipts.scope_write_receipts_finalizer", Attribute: "old_transition", Value: ""},
	{Kind: "trigger", Identity: "sync.scope_write_receipts.scope_write_receipts_finalizer", Attribute: "timing", Value: "after"},
	{Kind: "trigger", Identity: "sync.server_source_reservations.server_source_reservations_guard", Attribute: "arguments", Value: "[]"},
	{Kind: "trigger", Identity: "sync.server_source_reservations.server_source_reservations_guard", Attribute: "constraint", Value: ""},
	{Kind: "trigger", Identity: "sync.server_source_reservations.server_source_reservations_guard", Attribute: "enabled", Value: "O"},
	{Kind: "trigger", Identity: "sync.server_source_reservations.server_source_reservations_guard", Attribute: "events", Value: "insert,update,delete"},
	{Kind: "trigger", Identity: "sync.server_source_reservations.server_source_reservations_guard", Attribute: "function", Value: "sync.guard_server_source_reservation()"},
	{Kind: "trigger", Identity: "sync.server_source_reservations.server_source_reservations_guard", Attribute: "level", Value: "row"},
	{Kind: "trigger", Identity: "sync.server_source_reservations.server_source_reservations_guard", Attribute: "new_transition", Value: ""},
	{Kind: "trigger", Identity: "sync.server_source_reservations.server_source_reservations_guard", Attribute: "old_transition", Value: ""},
	{Kind: "trigger", Identity: "sync.server_source_reservations.server_source_reservations_guard", Attribute: "timing", Value: "before"},
}
